// website/supreme/React/src/layouts/LayoutAlternative.js
import React from 'react';
import Header from '../components/layout/Header';
import Footer from '../components/layout/Footer02';

const LayoutAlternative = ({ children }) => (
  <React.Fragment>
    <Header navPosition="right" />
    <main className="site-content">
      {children}
    </main>
    <Footer topDivider className="illustration-section-08" />
  </React.Fragment>
);

export default LayoutAlternative;

// website/supreme/Vue/src/layouts/LayoutAlternative.vue
<template>
    <fragment>
        <c-header nav-position="right" />
        <main class="site-content">
            <slot />
        </main>
        <c-footer topDivider class="illustration-section-08" />
    </fragment>
</template>

<script>
import CHeader from '@/components/layout/Header.vue'
import CFooter from '@/components/layout/Footer02.vue'
export default {
  components: {
    CHeader,
    CFooter
  }
}
</script>
